# Use Python base image
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy runner script into image
COPY runner.py .

# Default command to run Python code
CMD ["python", "runner.py"]
